services:
  app:
    build: .
    container_name: laravel_app
    networks:
      - web
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: var/www/html/database/database.sqlite
      DB_FOREIGN_KEYS: "true"
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=80

  traefik:
      image: traefik:v2.10
      container_name: traefik
      command:
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
        - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
        - "--certificatesresolvers.myresolver.acme.email=tonemail@domaine.com"
        - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      ports:
        - "81:80"
        - "443:443"
      networks:
        - web
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
        - "./traefik/letsencrypt:/letsencrypt"

networks:
  web: 
    external: false
  # db:
  #   image: sqlite:3
  #   container_name: laravel_db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: admin
  #     MYSQL_DATABASE: laravel
  #     MYSQL_USER: laravel
  #     MYSQL_PASSWORD: secret
  #   ports:
  #     - "3307:3306"
