# traefik.yml
api:
  dashboard: true          # Dashboard accessible sur le port configuré
  insecure: false          # Ne pas exposer en production

entryPoints:
  web:
    address: ":80"         # HTTP
  websecure:
    address: ":443"        # HTTPS

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false  # Seuls les containers avec labels seront exposés

certificatesResolvers:
  myresolver:
    acme:
      email: bouldoires.emmanuel@gmail.com      # Remplace par ton email
      storage: /letsencrypt/acme.json
      tlsChallenge: true
